# @file site.yml
---
- name: Install node + npm packages
  hosts: 127.0.0.1
  connection: local
  # become: yes
 
  # tasks:
  #   - include: roles/common/tasks/epelrepo.yml
  #   - name: 'install git'
  #     yum: name=git state=latest
  #   - include: roles/common/tasks/redis.yml
  #   - include: roles/common/tasks/nodejs.yml
  #     vars:
  #       node_version: '0.10.28'
  #       nodebrew_path: '.nodebrew/current/bin'
  #   - include: roles/common/tasks/hubot.yml
  #     vars:
  #       nodebrew_path: '.nodebrew/current/bin'
  #       project_dir: "/home/vagrant/beatbot"

  roles:
    # - testnode
    - epelrepo
    - git
    - redis
    - perl
    - nodebrew
    - gulp
    - yeoman
    # - bower
    - coffee
    - hubot