---
- name: npm install hubot
  command: npm install -g hubot
  become: no
  environment:
    PATH: "/home/vagrant/{{ nodebrew_path }}:{{ ansible_env.PATH }}"

- name: install libicu-devel
  yum: name=libicu-devel state=latest
  sudo: yes